grpc_url = "http://cosmos-grpc.polkachu.com"
grpc_port = "14990"
chain_id = "cosmoshub-4"
chain_denom = "uatom"
deposit_denom = "ibc/DBD9E339E1B093A052D76BECFFDE8435EAC114CF2133346B4D691F3F2068C957"
ica_address = "cosmos1azgqx3ug78fxg45pf4wpzcy43yzrhag9svya26ccxq3zwpedcd4ssk5efy"
