grpc_url = "http://grpc-keragon.cosmoshub-4.neutron.org"
grpc_port = "80"
chain_id = "cosmoshub-4"
chain_denom = "uatom"
deposit_denom = "ibc/DBD9E339E1B093A052D76BECFFDE8435EAC114CF2133346B4D691F3F2068C957"
ica_address = "cosmos1zn6es65nz4w2j9d9dx05p5al3m06s49tys08hge9yj5gfdxq5ceqxyypax"
