grpc_url = "https://<...>"
grpc_port = "443"
chain_id = "ledger-mainnet-1"
chain_denom = "ulom"
deposit_denom = "ibc/DBD9E339E1B093A052D76BECFFDE8435EAC114CF2133346B4D691F3F2068C957"
ica = "lom1g8p66wfxmvvknv5w23ntxsl9wj8rr4923zfquk8tw8kemrlz8rks8m7fn7"
entry_contract = "lom1szrfu43ncn6as3mgjd8davelgd77zdj7n3zhwkuc8w85gc3yrctsdrnnxl"
callback_contract = "lom13ehuhysn5mqjeaheeuew2gjs785f6k7jm8vfsqg3jhtpkwppcmzqdk2xf9"
eureka_denom = "ibc/EB19395F41C98C5F53420B7F8A96A02D075F86E5E8B90B88EE0D6C63A32F9040"
native_denom = "uclbtc"
