grpc_url = "http://rpc.neutron.quokkastake.io"
grpc_port = "9090"
chain_id = "neutron-1"
mars_credit_manager = "neutron1scjuh29rzffqzhgxusjd56f7qnf7r9e6rwxym6n65h9d3kkhfrqs0xm4dn"
supervault = "neutron1720ank30032ml4h6rsygv0j9q4kdg9yr5g57yn55rmw3mnstg24q2keq2y"
authorizations = "neutron1v47q4jks87v58cldgujdc6qx7ej75lku84hm7cmm27as742qzcls56s0fw"
processor = "neutron1mksu8tf7mjxupl5kvshtqdca77gteqyczulp3y5dgxa5ry2ewadsmsjjea"

[denoms]
deposit_token = "ibc/B7BF60BB54433071B49D586F54BD4DED5E20BEFBBA91958E87488A761115106B"
ntrn = "untrn"
supervault_lp = "factory/neutron1720ank30032ml4h6rsygv0j9q4kdg9yr5g57yn55rmw3mnstg24q2keq2y/BTC-BTC"

[accounts]
gaia_ica = "neutron16hktqc6tfe5m9r2z847h0nr65mptxlyp6h0n6fllt38mnwrfhm7sc6j34e"
lombard_ica = "lom1g8p66wfxmvvknv5w23ntxsl9wj8rr4923zfquk8tw8kemrlz8rks8m7fn7"
deposit = "neutron188wy5z08echndrnff9juglfpe3637jkgkl36v63kk6z5h50tys0qslqlfa"
mars_deposit = "neutron1a86egmmxxn94xfl30dykltpn9q848re73x2w8rh0kh9pdxxl7vaqp7vjdh"
supervault_deposit = "neutron14rrmpkume26lnwfgh5ssjrcsvy3nasmgetf2hmx9cghyjl850knqgvkntd"
settlement = "neutron17pnvrfch0t3g0w7980pyhurhjp6j9306wzn6psj8kq70wfe9guesrdfyc8"

[libraries]
deposit_splitter = "neutron1ft9xkesl4f6wvy233jdpzwzaac47nn7j0yrdnk9eywdzcppl507qd5z4gd"
mars_lending = "neutron18eaahq5d2uzxj9qkkrhtp2u4juwvc3fhfn5flz4pzefwc58r865qa3pmy2"
supervault_lper = "neutron1tgy2nr906sk74l8zmvw698ldkps5jm3lzneclgjeqjte8vrpquysmr632g"
clearing_queue = "neutron1yu2p505pw5u7rkm5gdmefl3mexfv9d9mzmt598swcwwmedt3frjseyndzf"
ica_transfer_gaia = "neutron1mvmppwufzj5s0r6d5sqtm7e6f87kqgxhl8ngav5sjx4uay75tfjsu7reag"
phase_shift_maxbtc_issuer = "neutron1mdfzgkq7675dwwcq37mxjzamfdnz6d5umt05txcwj78y7a22p4cqr670kg"
phase_shift_forwarder = "neutron14ffay82cwdsnm222v4gcl3pakjs3zdlcr3rmz6cpt9vejevxklpq32ferr"
phase_shift_supervault_withdrawer = "neutron105rg297c7xwm4glyh62j98lpcrjmln037knyhna9vcmvt73dfcrs55ywl3"

[coprocessor_app_ids]
clearing_queue = "077341f90e2faa8e710b1a7e6e575104da40beaf0787d22c49d9c53f965d5816"
