grpc_url = "http://grpc-lb.neutron.org"
grpc_port = "80"
chain_id = "neutron-1"
mars_credit_manager = "neutron1scjuh29rzffqzhgxusjd56f7qnf7r9e6rwxym6n65h9d3kkhfrqs0xm4dn"
supervault = "neutron1720ank30032ml4h6rsygv0j9q4kdg9yr5g57yn55rmw3mnstg24q2keq2y"
authorizations = "neutron1xqyqauhh68f06qmgq2392vhx4lh920d4dyysljzxl4sp8a3lpeasyvms63"
processor = "neutron1l76m4chl8xjkkmtdepzp57gl02ruh0dqldepxlua6awphhnya6vqvadjmf"

[denoms]
deposit_token = "ibc/B7BF60BB54433071B49D586F54BD4DED5E20BEFBBA91958E87488A761115106B"
ntrn = "untrn"
supervault_lp = "factory/neutron1720ank30032ml4h6rsygv0j9q4kdg9yr5g57yn55rmw3mnstg24q2keq2y/BTC-BTC"

[accounts]
gaia_ica = "neutron15qleevl7mlh76xaxwea5jupavu3j8klknvyyqj6mf06dwp5paf7s7nd7n2"
lombard_ica = "lom1g8p66wfxmvvknv5w23ntxsl9wj8rr4923zfquk8tw8kemrlz8rks8m7fn7"
deposit = "neutron1w6h4fdqcej54wwya6t62fzd4r6aer7f5ulh02y7grs6r6ppun98sksaeeq"
mars_deposit = "neutron18elaf6dse3q96mjfnk2ycphkpkw7lca0mdvypnaynzt9r6drk4zqa2ygk5"
supervault_deposit = "neutron1aqytfefeua54g26msdsv7rya5jryn4rua6fsfvgnjryem8ze03mqqk4qyd"
settlement = "neutron1aahayz2gdxlpkcqs6nyn52mz7dpha0hzgdcvreluarxnevl8escs9hz70l"

[libraries]
deposit_splitter = "neutron1vq645lxlcp0dgnm8xrcy8uasdn0t0kna8q4ttwsh0p3n4pkv92eqhquxzt"
mars_lending = "neutron17ujhtrx6xsnf5dp9yt8h6mvfjf7atlmlfgl3r4ktv52e9l3h4s9qm522rd"
supervault_lper = "neutron1cy4yq0c5eky7kung9dwkateqepmhf0xg9zyk9ppt8qkf9cq6g7pq72arja"
clearing_queue = "neutron1a4uxz0x3t6lm0fzuplrz0nhasgf42gd6nvuashmwj8lepggnsn5qdyrm9f"
ica_transfer_gaia = "neutron14q0g9psdk7tuswavxqqtd0y5csawaen86eyfu0g72d4xnzcw64qs4m2fwt"
phase_shift_maxbtc_issuer = "neutron1z5d543syuxfje6lrqs3p6hwzunxmdg030ct6wllql6d9tw0ctk6s0cn0y7"
phase_shift_forwarder = "neutron1n72d85qr29haw8wnrlc2pdpvyygnefhszq3lvc53lz506f494fssgew3wz"
phase_shift_supervault_withdrawer = "neutron1nmn2sjmewauxyuyktylnhynqp6h2d4y6s5k7g407u670jffry73s44pn5d"

[coprocessor_app_ids]
clearing_queue = "26f7c483dba8d191bc52d389c64e21c6cbcbb1f61fcbaa79653e6f5f3d0f24c0"
