grpc_url = "http://rpc.neutron.quokkastake.io"
grpc_port = "9090"
chain_id = "neutron-1"
min_ibc_fee = "1"
mars_credit_manager = "neutron1scjuh29rzffqzhgxusjd56f7qnf7r9e6rwxym6n65h9d3kkhfrqs0xm4dn"
supervault = "neutron1720ank30032ml4h6rsygv0j9q4kdg9yr5g57yn55rmw3mnstg24q2keq2y"
authorizations = "neutron1692gg6kcpa8vez604ajycfz28033vajmnfncf3dga562vxldk4nsq0fryd"
processor = "neutron1rk995ysp345fxl2vwzvhuc8q06wqtp9avhserul6a9vk7f72509q67lggt"

[denoms]
deposit_token = "ibc/B7BF60BB54433071B49D586F54BD4DED5E20BEFBBA91958E87488A761115106B"
ntrn = "untrn"
supervault_lp = "factory/neutron1720ank30032ml4h6rsygv0j9q4kdg9yr5g57yn55rmw3mnstg24q2keq2y/BTC-BTC"

[accounts]
gaia_ica = "neutron13gmyrza00x60uu869fr8z0895rzw8kcwcecqs2zemps3d7lk9rvq3qz6qe"
lombard_ica = "lom1g8p66wfxmvvknv5w23ntxsl9wj8rr4923zfquk8tw8kemrlz8rks8m7fn7"
deposit = "neutron1r2kmdxn4jxaxxe2u978sus3xewcx2xw28gzdk68mp7frw8vstskskqunq0"
mars_deposit = "neutron1hg0wsg2emd7tju2xv5j5tznlycssgmkupyl8u9rddg90u6t23wgq2e96ej"
supervault_deposit = "neutron1vuh4ha79m587l54nml2ukk4lqvp44dqh6enynhsfpal4fr8lvkps5jsedq"
settlement = "neutron1u5j6npevgzjjeafc3mjagsallf4czmrk22vx6zq7g9yh4ugvjdpq00p4cp"

[libraries]
deposit_splitter = "neutron1468jad4wzhtwcradx4y62qx0kys7945rzamxcayylu0p4ads4x3sfdj2nc"
mars_lending = "neutron1nndj9qznhahwc5hl05kwl5zncw3tzfn0f68a2ea8qxluh8fhm2yq79503x"
supervault_lper = "neutron1znr9l06flktkdkpru7gclmyg63ufnwxauldvrkm60a9v7n7z4jesh8xx5w"
clearing_queue = "neutron1pdp6mty3ykchjxksj9hakupma3atyrah27mtws3ph2matjkhg7qse70m8g"
ica_transfer_gaia = "neutron1dfddm3p6jtk6pwfr4etteu02udxnux4mcrkzecv0n4auuwea9guq8ja4er"
phase_shift_maxbtc_issuer = "neutron1ht6qw28szug37v4ujy3q06ggduf0tyuncsezt0p8spgxvyzcfxgq6p25et"
phase_shift_forwarder = "neutron16fvj5q8z77uxukaw6cd2ffdavqs52jdmh876emcvynfpnq05wj6q6phcuh"
phase_shift_supervault_withdrawer = "neutron175zy3vdce3f9yypqlypwpdpfe4z5zps5kx24rng2ajhqkjs0x87qec6fnn"

[coprocessor_app_ids]
clearing_queue = "17ce01c71c687c7599901b2f0a37bf3d8188c7d1bcde03abe7382b3824a6dfc8"
