grpc_url = "http://grpc-xyphion.neutron-1.neutron.org"
grpc_port = "80"
chain_id = "neutron-1"
supervault = "neutron1z4qky902yes9zl5eruwgdd2pgtlyeglunc0escf0a7n2xeyw97gqcr7u5u"
authorizations = "neutron16qvvfpchnpl0jhxnsdzlrnseruc5qsspkz6l3ke5u4vywjrn4h8qzqkcq0"
processor = "neutron1f0wk2dsu6ycdu8qh335a8t78wdhx4yscc9mjy6w6t09ggry0jgrqfumagt"

[denoms]
deposit_token = "ibc/B559A80D62249C8AA07A380E2A2BEA6E5CA9A6F079C912C3A9E9B494105E4F81"
ntrn = "untrn"
supervault_lp = "factory/neutron1z4qky902yes9zl5eruwgdd2pgtlyeglunc0escf0a7n2xeyw97gqcr7u5u/BTC-USDC"

[accounts]
deposit = "neutron1fgqqjvjjscttlllcaqe30ykapnm48fw7jc0453d9fwgwxdyzzvyqj0ke5c"
settlement = "neutron1dx9w3pzgmw37w8cdpchetvqwqyfsjv206ge80707wuqdllfsdywsjht2ce"

[libraries]
supervault_lper = "neutron1jp46ul7sxxuww76dg6cjd7hy7eunecnvt56nl03c8up32wjat6ps8jvtx7"
clearing_queue = "neutron1y65pzxctp2z8pw688fph9jwxmwa5c8l25h3l6j45txzru52y8xuqdamwfp"

[coprocessor_app_ids]
clearing_queue = "365fa6337269d3e0ad62c9d8483ce337297bb37f4014795ba449f3ad8d3ac95f"
