[general]
rpc_url = "https://eth-mainnet.public.blastapi.io"
owner   = "0xF4be64577425b84aE62EdF38b4b695771a1d6538" # Neutron multisig address

[vault]
deposit_token            = "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48" # USDC on Ethereum
strategist               = "0xF4be64577425b84aE62EdF38b4b695771a1d6538" # Address of the strategist
platform_fee_account     = "0xF4be64577425b84aE62EdF38b4b695771a1d6538" # Receiver of the platform fees portion
strategist_fee_account   = "0xF4be64577425b84aE62EdF38b4b695771a1d6538" # Receiver of the strategist fees portion
strategist_fee_ratio_bps = 5000                                         # Strategist fee is 50%, rest goes to the platform (50%)
scaling_factor           = "1000000000000"                              # scaling factor for rate updates
deposit_cap              = "100000000000"                               # e.g. 100K USDC
deposit_fee_bps          = 100                                          # 1% deposit fee
withdraw_fee_bps         = 100                                          # 1% withdraw fee
max_rate_increment_bps   = 2000                                         # 20% maximum rate increment per update
max_rate_decrement_bps   = 2000                                         # 20% maximum rate decrement per update
starting_rate            = "1000000"                                    # 1e6 - USDC Precision - 6 decimals
min_rate_update_delay    = 10                                           # 10 seconds - Minimum delay for rate updates
max_rate_update_delay    = 345600                                       # 4 days in seconds - Maximum delay for rate updates before vault gets paused

[eureka_transfer]
handler                    = "0xfc2d0487a0ae42ae7329a80dc269916a9184cf7c"
recipient                  = "cosmos1ms4d5gyatxrt0suum2cs5hp63kjzcyhux6lkaydzgu4qw234qzrsvr2m0v"
source_client              = "cosmoshub-0"
timeout                    = 43200                                                               # 12 hours in seconds
ibc_transfer_threshold_amt = 1000000

[coprocessor_app]
eureka_transfer_coprocessor_app_id = "" # TBD after we have the app deployed
