[workspace]
members  = ["types", "deploy", "strategist"]
resolver = "2"

[workspace.dependencies]
cosmwasm-std                         = { version = "2.1.3" }
cosmrs                               = { version = "0.21.1" }
serde                                = { version = "1.0.207", default-features = false, features = ["derive"] }
dotenv                               = "0.15"
tokio                                = { version = "1.45.1", features = ["macros", "rt-multi-thread"] }
valence-domain-clients               = { git = "https://github.com/timewave-computer/valence-domain-clients.git", branch = "main" }
alloy                                = { version = "0.9.2", features = ["full"] }
hex                                  = "0.4.3"
valence-authorization-utils          = { git = "https://github.com/timewave-computer/valence-protocol", branch = "neutron-vaults" }
valence-processor-utils              = { git = "https://github.com/timewave-computer/valence-protocol", branch = "neutron-vaults" }
valence-library-utils                = { git = "https://github.com/timewave-computer/valence-protocol", branch = "neutron-vaults" }
valence-account-utils                = { git = "https://github.com/timewave-computer/valence-protocol", branch = "neutron-vaults" }
valence-ica-ibc-transfer             = { git = "https://github.com/timewave-computer/valence-protocol", branch = "neutron-vaults" }
valence-mars-lending                 = { git = "https://github.com/timewave-computer/valence-protocol", branch = "neutron-vaults" }
valence-supervaults-lper             = { git = "https://github.com/timewave-computer/valence-protocol", branch = "neutron-vaults" }
valence-supervaults-withdrawer       = { git = "https://github.com/timewave-computer/valence-protocol", branch = "neutron-vaults" }
valence-clearing-queue-supervaults   = { git = "https://github.com/timewave-computer/valence-protocol", branch = "neutron-vaults" }
valence-dynamic-ratio-query-provider = { git = "https://github.com/timewave-computer/valence-protocol", branch = "neutron-vaults" }
valence-splitter-library             = { git = "https://github.com/timewave-computer/valence-protocol", branch = "neutron-vaults" }
valence-forwarder-library            = { git = "https://github.com/timewave-computer/valence-protocol", branch = "neutron-vaults" }
valence-verification-gateway         = { git = "https://github.com/timewave-computer/valence-protocol", branch = "neutron-vaults" }
valence-strategist-utils             = { git = "https://github.com/timewave-computer/valence-protocol", branch = "neutron-vaults" }
valence-maxbtc-issuer                = { git = "https://github.com/timewave-computer/valence-protocol", branch = "neutron-vaults" }
log                                  = { version = "0.4.22" }
valence-lending-utils                = { git = "https://github.com/timewave-computer/valence-protocol", branch = "neutron-vaults" }
serde_json                           = { version = "1.0.140", default-features = false, features = ["alloc"] }
