[workspace]
members  = ["types", "deploy", "strategist"]
resolver = "2"

[workspace.dependencies]
cosmwasm-std = { version = "2.1.3" }
serde        = { version = "1.0.207", default-features = false, features = ["derive"] }
