[code_ids]
maxbtc_issuer                = 3928
mars_lending                 = 3933
splitter_library             = 3929
processor                    = 3934
clearing_queue_supervaults   = 4078
forwarder_library            = 3925
ica_ibc_transfer             = 3936
supervaults_withdrawer       = 3932
dynamic_ratio_query_provider = 3926
interchain_account           = 3927
supervaults_lper             = 3931
authorization                = 3937
base_account                 = 3930
