grpc_url = "http://grpc-xyphion.neutron-1.neutron.org"
grpc_port = "80"
chain_id = "neutron-1"
mars_credit_manager = "neutron1scjuh29rzffqzhgxusjd56f7qnf7r9e6rwxym6n65h9d3kkhfrqs0xm4dn"
fbtc_supervault = "neutron1ct00dzd944axt0pw9ak25a3ar40n8tmdwwnqxv6dpxxy6v3ysz9sw7n3jd"
lbtc_supervault = "neutron1720ank30032ml4h6rsygv0j9q4kdg9yr5g57yn55rmw3mnstg24q2keq2y"
solvbtc_supervault = "neutron1vve4kr2j8ftydrh3gjqpns4p86l8x5unpvvheqdwlhpvawarea2suu8972"
ebtc_supervault = "neutron1s8k6gcrnsfrs9rj3j8757w4e0ttmzsdmjvwfwxruhu2t8xjgwxaqegzjgt"
pumpbtc_supervault = "neutron16x9rk787mdaatmd58cevex6sc3p55uhshjmzyf3aa9atx0dgauvs8u8tj0"
bedrockbtc_supervault = "neutron1704tmu9nvgk0l8xmpua0su6dq3r89mht0adlx8gxte695qapstks6lzmma"
maxbtc_supervault = "TBD"
authorizations = "neutron18mlmd0u7xnzjns6np4z3fd8ph096zp4w0tkacfra9awzr8gftxtqsh23z4"
processor = "neutron1lfp6vc4gvpp6a7f6y07qqq9v80hlzu7xdev5vw34dz7268ta6k3q9e4uwn"

[denoms]
deposit_token = "ibc/0E293A7622DC9A6439DB60E6D234B5AF446962E27CA3AB44D0590603DFF6968E"
ntrn = "untrn"
fbtc_supervault_lp = "factory/neutron1ct00dzd944axt0pw9ak25a3ar40n8tmdwwnqxv6dpxxy6v3ysz9sw7n3jd/BTC-BTC"
lbtc_supervault_lp = "factory/neutron1720ank30032ml4h6rsygv0j9q4kdg9yr5g57yn55rmw3mnstg24q2keq2y/BTC-BTC"
solvbtc_supervault_lp = "factory/neutron1vve4kr2j8ftydrh3gjqpns4p86l8x5unpvvheqdwlhpvawarea2suu8972/BTC-BTC"
ebtc_supervault_lp = "factory/neutron1s8k6gcrnsfrs9rj3j8757w4e0ttmzsdmjvwfwxruhu2t8xjgwxaqegzjgt/BTC-BTC"
pumpbtc_supervault_lp = "factory/neutron16x9rk787mdaatmd58cevex6sc3p55uhshjmzyf3aa9atx0dgauvs8u8tj0/BTC-BTC"
bedrockbtc_supervault_lp = "factory/neutron1704tmu9nvgk0l8xmpua0su6dq3r89mht0adlx8gxte695qapstks6lzmma/BTC-BTC"
maxbtc_supervault_lp = "TBD"

[accounts]
ica = "neutron1sz73n9elzp2ngrvq53j6fh7wf4ktp7wurjfunsgg7pcgwm8t28psuamecp"
deposit = "neutron133jsumfz3l8m0r2ct8x2jyuma88la04vx8tf06q9wj5ewp0w9t3snd6ktw"
mars_deposit = "neutron1k5f6pll033hjdeeqktjf06daunwhlfun9q3cjcdu4qfh2zf4qw0qsgcyra"
fbtc_supervault_deposit = "neutron1m9xwhwachy8ekxjs4k8n602q4pgkkv5sc7w0wfq0e0zjkpneuhgqsd03ar"
lbtc_supervault_deposit = "neutron18fg4764jnja54cmm8yglrfxukd745jg3g4l3qdg32gkzanvnhmmqhe7h5u"
solvbtc_supervault_deposit = "neutron1d3paqhep00sm2kj7zecp6vy7e07ugcep5zzetmvn8ycft9jflazsan2ywn"
ebtc_supervault_deposit = "neutron1k2tn56pnzd4t9qu70z9mn5eltqqnqy7yg0nd6cmf6ewz5sf2tn4qe63mf6"
pumpbtc_supervault_deposit = "neutron1qmufj83sdntlylwlg05nwayzdc3dckdygapsg73qy5wk99vgzeqs2e97jj"
bedrockbtc_supervault_deposit = "neutron1pas6wdygtwafnq7fq708uzzckds8penmd053p7sf9u2d5szgvgpqaptn6a"
maxbtc_supervault_deposit = "neutron18u2dk9hvv0m8rr7v94fn0qf5e03ssen8awnxr2a3npqs24jws3ksysvdpn"
settlement = "neutron14rz4fvdv966zrt6cjxhfd9ade8h6rscsjku8wrldrgtqre5lw5cq64tg0k"

[libraries]
deposit_splitter = "neutron14xpg7xhgcqpgukelvy2eqdr549gyfsgwhrnqcrrakr3eyjrrzyhqrpraef"
dynamic_ratio_query_provider = "neutron1je6z6mqzy7338a6j0r9xj3rppveaga7km75gnx5s785zu0nj85uqpu74xm"
mars_lending = "neutron1kxqdv3rnlh56snlyt0wzjrg7snha705489lzuc6gr7f3a4ygkysqz7c4ke"
fbtc_supervault_lper = "neutron1yx0juh2g2f0dg8edl2736tv84h8dznhy9wgxn8qz7v4apla40rusf3g52e"
lbtc_supervault_lper = "neutron1pkzcrapj3nw3kna3ycs8m7scnwt69tt5edam83njv6thm4tpdjmq77dtpm"
solvbtc_supervault_lper = "neutron1tkfpf78q690q6u0fummxezw7ua5qc3lv6364f2y8q2utvhr0n57qkk3q2z"
ebtc_supervault_lper = "neutron13zv7vpn0rde9tqjz90p8grgrqsulgjdfzpk3u5tvxktw32emzrgq90llmf"
pumpbtc_supervault_lper = "neutron1ppzrjt9rsu5vkepq9zsup67nxhpc2smdtxdn03m8sl88fau5ehaqyguau6"
bedrockbtc_supervault_lper = "neutron1lgrhgvxypteu5kntrvqe83ahsgf7vqews0q5e6tll2mhla0tffrqje47ms"
maxbtc_supervault_lper = "neutron1y5s97wuj8497dcc33d320z6eugeuk94legtg9rqcgttzctg9fp0sz4vhk7"
clearing_queue = "neutron1uwpdsf02sweyedgk842adnpxlrs7a0htafnsj9vkc6hp0nmxwt7sc9qk0f"
ica_transfer = "neutron19969umlq4u0cghtdxn9kn29wnd6krycevw8ljfzej3fgnyrv9afqc89w8p"
phase_shift_maxbtc_issuer = "neutron1xk3l2cykt2huwy2zsarr2ylghwt84s4ljs9pl9vu47tgs49qmcvsc7mpmp"
phase_shift_splitter = "neutron1pucydasnads90vaazmx00kpeajjfw5jum4sln9nkjp9cd7rv76tq3l62rj"
phase_shift_forwarder = "neutron1k3lkhc946886k6m5gn6qrr9nwakvuka9y49hnf2nrx3kkhvewyps27ec9c"
phase_shift_fbtc_supervault_withdrawer = "neutron13dm0vmaly8x5yvcezm6wak2azhysv4lfrlatjn35qxlhjshy3cqshjuvxr"
phase_shift_lbtc_supervault_withdrawer = "neutron1nes89s260ek4yy5cjcwz3smg50laj5nsx4a0k7796h53fktylkcsgcxet6"
phase_shift_solvbtc_supervault_withdrawer = "neutron176aesu5n5lrr5dylfckcyp9rgwldul5tm5gk8s3uvn0krver48eqlwlj9f"
phase_shift_ebtc_supervault_withdrawer = "neutron1rxn0necqzq7tce2ndugxkpmkkt56gg8gwq2eaxgel35s9dgufrgs6e6hzk"
phase_shift_pumpbtc_supervault_withdrawer = "neutron10vmlfqxprn3mhvxca95kq5gnwnvpxhhlnc6ldu07upf9qsdqdnlswgqjpl"
phase_shift_bedrockbtc_supervault_withdrawer = "neutron173knac3p7amj5jgy8zjr4r82948yz879he2s5dgq3wkqnyak52vs0sptrn"

[coprocessor_app_ids]
clearing_queue = "c979bf2a0d9057ecdc8bde11f8cfa98aca9f9e9b1bda6d7ae8443512bd138ce8"
