[general]
grpc_url      = "http://rpc.neutron.quokkastake.io"
grpc_port     = "9090"
chain_id      = "neutron-1"
owner         = "neutron17w0xj03v3jj7tj8uz998ga6he93ytxggnrf8zr" # Should be Neutron multisig
strategist    = "neutron17w0xj03v3jj7tj8uz998ga6he93ytxggnrf8zr" # Should be strategist address

[ica]
deposit_token_on_hub_denom = "ibc/D742E8566B0B8CC8F569D950051C09CF57988A88F0E45574BFB3079D41DE6462" # WBTC
channel_id                 = "channel-569"                                                          # Hub -> Neutron channel
ibc_transfer_timeout       = 600                                                                    # 10 minutes
connection_id              = "connection-0"                                                         # Neutron -> Hub connection
ica_timeout                = 43200                                                                  # 12 hours in seconds - Large value recommended: https://docs.neutron.org/neutron/modules/interchain-txs/messages

[program]
deposit_token_on_neutron_denom = "ibc/0E293A7622DC9A6439DB60E6D234B5AF446962E27CA3AB44D0590603DFF6968E"               # WBTC

mars_credit_manager            = "neutron1scjuh29rzffqzhgxusjd56f7qnf7r9e6rwxym6n65h9d3kkhfrqs0xm4dn"                 # Need to figure this out, not sure if this one

fbtc_supervault                = "neutron1ct00dzd944axt0pw9ak25a3ar40n8tmdwwnqxv6dpxxy6v3ysz9sw7n3jd"                 # TBD
fbtc_supervault_asset1         = "ibc/0E293A7622DC9A6439DB60E6D234B5AF446962E27CA3AB44D0590603DFF6968E"               # TBD
fbtc_supervault_asset2         = "ibc/2EB30350120BBAFC168F55D0E65551A27A724175E8FBCC7B37F9A71618FE136B"               # TBD
fbtc_supervault_lp_denom       = "factory/neutron1ct00dzd944axt0pw9ak25a3ar40n8tmdwwnqxv6dpxxy6v3ysz9sw7n3jd/BTC-BTC" # TBD after supervaults are deployed

lbtc_supervault                = "neutron1720ank30032ml4h6rsygv0j9q4kdg9yr5g57yn55rmw3mnstg24q2keq2y"                 # TBD
lbtc_supervault_asset1         = "ibc/0E293A7622DC9A6439DB60E6D234B5AF446962E27CA3AB44D0590603DFF6968E"               # TBD
lbtc_supervault_asset2         = "ibc/B7BF60BB54433071B49D586F54BD4DED5E20BEFBBA91958E87488A761115106B"               # TBD
lbtc_supervault_lp_denom       = "factory/neutron1720ank30032ml4h6rsygv0j9q4kdg9yr5g57yn55rmw3mnstg24q2keq2y/BTC-BTC" # TBD after supervaults are deployed

solvbtc_supervault             = "neutron1vve4kr2j8ftydrh3gjqpns4p86l8x5unpvvheqdwlhpvawarea2suu8972"                 # TBD
solvbtc_supervault_asset1      = "ibc/0E293A7622DC9A6439DB60E6D234B5AF446962E27CA3AB44D0590603DFF6968E"               # TBD
solvbtc_supervault_asset2      = "ibc/C0F284F165E6152F6DDDA900537C1BC8DA1EA00F03B9C9EC1841FA7E004EF7A3"               # TBD
solvbtc_supervault_lp_denom    = "factory/neutron1vve4kr2j8ftydrh3gjqpns4p86l8x5unpvvheqdwlhpvawarea2suu8972/BTC-BTC" # TBD after supervaults are deployed

ebtc_supervault                = "neutron1s8k6gcrnsfrs9rj3j8757w4e0ttmzsdmjvwfwxruhu2t8xjgwxaqegzjgt"                 # TBD
ebtc_supervault_asset1         = "ibc/0E293A7622DC9A6439DB60E6D234B5AF446962E27CA3AB44D0590603DFF6968E"               # TBD
ebtc_supervault_asset2         = "ibc/E2A000FD3EDD91C9429B473995CE2C7C555BCC8CFC1D0A3D02F514392B7A80E8"               # TBD
ebtc_supervault_lp_denom       = "factory/neutron1s8k6gcrnsfrs9rj3j8757w4e0ttmzsdmjvwfwxruhu2t8xjgwxaqegzjgt/BTC-BTC" # TBD after supervaults are deployed

pumpbtc_supervault             = "neutron16x9rk787mdaatmd58cevex6sc3p55uhshjmzyf3aa9atx0dgauvs8u8tj0"                 # TBD
pumpbtc_supervault_asset1      = "ibc/0E293A7622DC9A6439DB60E6D234B5AF446962E27CA3AB44D0590603DFF6968E"               # TBD
pumpbtc_supervault_asset2      = "ibc/1075520501498E008B02FD414CD8079C0A2BAF9657278F8FB8F7D37A857ED668"               # TBD
pumpbtc_supervault_lp_denom    = "factory/neutron16x9rk787mdaatmd58cevex6sc3p55uhshjmzyf3aa9atx0dgauvs8u8tj0/BTC-BTC" # TBD after supervaults are deployed

bedrockbtc_supervault          = "neutron1704tmu9nvgk0l8xmpua0su6dq3r89mht0adlx8gxte695qapstks6lzmma"                 # TBD
bedrockbtc_supervault_asset1   = "ibc/0E293A7622DC9A6439DB60E6D234B5AF446962E27CA3AB44D0590603DFF6968E"               # TBD
bedrockbtc_supervault_asset2   = "ibc/3F1D988D9EEA19EB0F3950B4C19664218031D8BCE68CE7DE30F187D5ACEA0463"               # TBD
bedrockbtc_supervault_lp_denom = "factory/neutron1704tmu9nvgk0l8xmpua0su6dq3r89mht0adlx8gxte695qapstks6lzmma/BTC-BTC" # TBD after supervaults are deployed

initial_split_mars_ratio       = "0.67"
initial_split_fbtc_ratio       = "0.0825"                                                                             # 25% of remaining 33%
initial_split_lbtc_ratio       = "0.0825"
initial_split_solvbtc_ratio    = "0.0495"                                                                             # 15% of remaining 33%
initial_split_ebtc_ratio       = "0.0495"
initial_split_pumpbtc_ratio    = "0.033"                                                                              # 10% of remaining 33%
initial_split_bedrockbtc_ratio = "0.033"

# This means 67 will be settled on Mars and 33% will be settled on Supervaults
mars_settlement_ratio = "0.67"
# For each supervault, what % of amount settled on Supervaults will be settled on it
fbtc_settlement_ratio_percentage       = 25
lbtc_settlement_ratio_percentage       = 25
solvbtc_settlement_ratio_percentage    = 15
ebtc_settlement_ratio_percentage       = 15
pumpbtc_settlement_ratio_percentage    = 10
bedrockbtc_settlement_ratio_percentage = 10
fbtc_denom                             = "ibc/2EB30350120BBAFC168F55D0E65551A27A724175E8FBCC7B37F9A71618FE136B" # TBD
lbtc_denom                             = "ibc/B7BF60BB54433071B49D586F54BD4DED5E20BEFBBA91958E87488A761115106B" # TBD
solvbtc_denom                          = "ibc/C0F284F165E6152F6DDDA900537C1BC8DA1EA00F03B9C9EC1841FA7E004EF7A3" # TBD
ebtc_denom                             = "ibc/E2A000FD3EDD91C9429B473995CE2C7C555BCC8CFC1D0A3D02F514392B7A80E8" # TBD
pumpbtc_denom                          = "ibc/1075520501498E008B02FD414CD8079C0A2BAF9657278F8FB8F7D37A857ED668" # TBD
bedrockbtc_denom                       = "ibc/3F1D988D9EEA19EB0F3950B4C19664218031D8BCE68CE7DE30F187D5ACEA0463" # TBD

[coprocessor_app]
clearing_queue_coprocessor_app_id = "c979bf2a0d9057ecdc8bde11f8cfa98aca9f9e9b1bda6d7ae8443512bd138ce8" # TBD after we have the app deployed
