[general]
rpc_url = "http://localhost:8545"
owner   = "0x54a37ac81263C482D6BE56F5Bd796e06e9Afa344" # Neutron multisig address
valence_owner = "0x54a37ac81263C482D6BE56F5Bd796e06e9Afa344" # TBD Owner of the verification gateway
coprocessor_root = "0x0000000000000000000000000000000000000000000000000000000000000000" # Bytes32 hash of coprocessor root

[vault]
deposit_token            = "0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599"
strategist               = "0x54a37ac81263C482D6BE56F5Bd796e06e9Afa344" # Address of the strategist
platform_fee_account     = "0x54a37ac81263C482D6BE56F5Bd796e06e9Afa344" # Receiver of the platform fees portion
strategist_fee_account   = "0x54a37ac81263C482D6BE56F5Bd796e06e9Afa344" # Receiver of the strategist fees portion
strategist_fee_ratio_bps = 500                                          # Strategist fee is 5%, rest goes to the platform (95%)
deposit_cap              = "10000000000000"                             # e.g. 10K BTC
deposit_fee_bps          = 100                                          # 1% deposit fee
withdraw_rate_bps        = 100                                          # 1% withdrawal rate
starting_rate            = "10000000"                                   # 1e8 - WBTC Precision
max_rate_update_delay    = 172800 # 48 hours in seconds - Maximum delay for rate updates before vault gets paused
rate_scaling_factor      = 1000000000000                                # scaling factor for rate updates

[eureka_transfer]
handler       = "0xfc2d0487a0ae42ae7329a80dc269916a9184cf7c"
recipient     = "cosmos1...."
source_client = "cosmoshub-0"
timeout       = 43200                                        # 12 hours in seconds

[coprocessor_app]
eureka_transfer_coprocessor_app_id = "..." # TBD after we have the app deployed
