grpc_url = "http://grpc-xyphion.neutron-1.neutron.org"
grpc_port = "80"
chain_id = "neutron-1"
mars_credit_manager = "neutron1qdzn3l4kn7gsjna2tfpg3g3mwd6kunx4p50lfya59k02846xas6qslgs3r"
authorizations = "neutron1mlf4lnzr2rspuwydf8g39una6ymjcytyegh4dn8csacjglly68yqy2qwy9"
processor = "neutron1wg26yfdpj63x6xaggj3sz4gaykckax20rury8a6y78pw64g3532qzgpcfu"

[denoms]
deposit_token = "ibc/B559A80D62249C8AA07A380E2A2BEA6E5CA9A6F079C912C3A9E9B494105E4F81"
ntrn = "untrn"

[accounts]
deposit = "neutron1h7n6635yk6cn6cedetdjp9mh6lv5sptd6avulwxlh5tcqhcadrms8q2p55"
settlement = "neutron17636kexjmyhujwkj0qlpjdwmu2p4n3txkp33fukfwx5dcm9c3lrqd84l8d"

[libraries]
mars_lending = "neutron15p45lrdxe5fdekaf8hr0qqudajzztderuucy0dx3xxcxhcvt48uspglhwm"
clearing_queue = "neutron1qmvm40x7fkdyrnq9x9pdr8gp7u4d7h87z7eensl2d42xmlnd0z4szzvtv4"

[coprocessor_app_ids]
clearing_queue = "077fc135b90f303b9bded904aae460ec29626847d7a72e9b78b1a3cfa2db3f67"
