grpc_url = "http://grpc-xyphion.neutron-1.neutron.org"
grpc_port = "80"
chain_id = "neutron-1"
mars_credit_manager = "neutron1qdzn3l4kn7gsjna2tfpg3g3mwd6kunx4p50lfya59k02846xas6qslgs3r"
authorizations = "neutron1fmmf7ywgzaxckt7aemnrmwd0ppjp8d7vha4mngdtpa89hvxz6s0svx2rq8"
processor = "neutron180hg7cwwx839dutfp0y6mkagcvpmkalpzt6revnex5sha8tsswdq5c5klc"

[denoms]
deposit_token = "ibc/B559A80D62249C8AA07A380E2A2BEA6E5CA9A6F079C912C3A9E9B494105E4F81"
ntrn = "untrn"

[accounts]
deposit = "neutron19w5plh5lqx5xqlfcrrmtdg60sav9snwq0p6gg6xjvvdjmfflnfnqes08ey"
settlement = "neutron1jafujkwnhhd43498m8p2y8e3v3u2p5uacaw7ake8hf2uxfzl4fhqfw0jfx"

[libraries]
mars_lending = "neutron17l8klkndmfv55ax8d0ahqtyn9vx0wp3dupy6g724n7tqcuaw428qdp0ayj"
clearing_queue = "neutron1h72eme9utxwgaay9l6ampewd67ewd4xx8rx7dmz0nlejf48pzv3qs0834h"

[coprocessor_app_ids]
clearing_queue = "78c43c62565739c6f1f4d78e74afed2b8daddc0a577e1145ffe6e29528f23940"
