[general]
rpc_url       = "https://eth-mainnet.public.blastapi.io"
owner         = "0xF4be64577425b84aE62EdF38b4b695771a1d6538" # Neutron multisig address

[vault]
deposit_token            = "0x8236a87084f8B84306f72007F36F2618A5634494"
strategist               = "0xF4be64577425b84aE62EdF38b4b695771a1d6538" # Address of the strategist
platform_fee_account     = "0xF4be64577425b84aE62EdF38b4b695771a1d6538" # Receiver of the platform fees portion
strategist_fee_account   = "0xF4be64577425b84aE62EdF38b4b695771a1d6538" # Receiver of the strategist fees portion
strategist_fee_ratio_bps = 5000                                         # Strategist fee is 50%, rest goes to the platform (50%)
scaling_factor           = "10000000000"                                # scaling factor for rate updates
deposit_cap              = "10000000000000"                             # e.g. 10K BTC
deposit_fee_bps          = 100                                          # 1% deposit fee
withdraw_fee_bps         = 100                                          # 1% withdraw fee
max_rate_increment_bps   = 2000                                         # 20% maximum rate increment per update
max_rate_decrement_bps   = 2000                                         # 20% maximum rate decrement per update
starting_rate            = "100000000"                                  # 1e8 - LBTC Precision - 8 decimals
min_rate_update_delay    = 300                                          # 5 minutes - Minimum delay for rate updates - for testing purposes
max_rate_update_delay    = 345600                                       # 4 days in seconds - Maximum delay for rate updates before vault gets paused

[eureka_transfer]
handler                    = "0xfc2d0487a0ae42ae7329a80dc269916a9184cf7c"
recipient                  = "lom13ehuhysn5mqjeaheeuew2gjs785f6k7jm8vfsqg3jhtpkwppcmzqdk2xf9" # Contract address that will handle the memo actions
source_client              = "ledger-mainnet-1"
timeout                    = 43200                                                            # 12 hours in seconds
ibc_transfer_threshold_amt = 1000000

[coprocessor_app]
eureka_transfer_coprocessor_app_id = "c99235e5282f36b73f413c2da2dfcb381b133ff58b0a029be2dbd926b614f256"
