[general]
rpc_url = "https://eth-mainnet.public.blastapi.io"
owner   = "0xd9A23b58e684B985F661Ce7005AA8E10630150c1" # Neutron multisig address
valence_owner = "0xd9A23b58e684B985F661Ce7005AA8E10630150c1" # TBD Owner of the verification gateway
coprocessor_root = "0x0000000000000000000000000000000000000000000000000000000000000000" # Bytes32 hash of coprocessor root

[vault]
deposit_token            = "0x8236a87084f8B84306f72007F36F2618A5634494"
strategist               = "0x510c4a1d637ff374399826f421003b775dc3e8dc" # Address of the strategist
platform_fee_account     = "0x510c4a1d637ff374399826f421003b775dc3e8dc" # Receiver of the platform fees portion
strategist_fee_account   = "0x510c4a1d637ff374399826f421003b775dc3e8dc" # Receiver of the strategist fees portion
strategist_fee_ratio_bps = 5000                                         # Strategist fee is 50%, rest goes to the platform (50%)
scaling_factor           = "1000000000000"                              # scaling factor for rate updates
deposit_cap              = "10000000000000"                             # e.g. 10K BTC
deposit_fee_bps          = 100                                          # 1% deposit fee
withdraw_rate_bps        = 100                                          # 1% withdrawal rate
starting_rate            = "100000000"                                  # 1e8 - LBTC Precision - 8 decimals
max_rate_update_delay    = 345600                                       # 4 days in seconds - Maximum delay for rate updates before vault gets paused

[eureka_transfer]
handler                    = "0xfc2d0487a0ae42ae7329a80dc269916a9184cf7c"
recipient                  = "lom13ehuhysn5mqjeaheeuew2gjs785f6k7jm8vfsqg3jhtpkwppcmzqdk2xf9" # Contract address that will handle the memo actions
source_client              = "ledger-mainnet-1"
timeout                    = 43200                                        # 12 hours in seconds
ibc_transfer_threshold_amt = 1000000

[coprocessor_app]
eureka_transfer_coprocessor_app_id = "a60592195f33238d599e801bde41bf5d79edabb3a5cb57f7056d969c8e93c655"
