grpc_url = "grpc_url"
grpc_port = "grpc_port"
chain_id = "chain_id"
chain_denom = "uatom"
deposit_denom = "ibc/DBD9E339E1B093A052D76BECFFDE8435EAC114CF2133346B4D691F3F2068C957"
ica_address = "cosmos1qh44ugsak6mejr60dsew5f0vaaxpl0pqhtzs2pudl37hkukk09aqjm5ex2"
