grpc_url = "http://rpc.neutron.quokkastake.io"
grpc_port = "9090"
chain_id = "neutron-1"
maxbtc_contract = "neutron1j4sl8nf7fkpsptqtcw6hmd6t27varth57gmjrrswfkr2t85sj8sqf6ncrh"
supervault_contract = "neutron1048engrh7u0ssphgfd8lgs05pyq7e4n9uh6u8g24f4uu23ay4s6qc0cm9g"
authorizations = "neutron1lrwt72sf9w2gqs2rj3sqg95eg7jyp7nl8np0tmrvupmevlawp39styd909"
processor = "neutron1t8h95xxfcfrn2dfd6z9uu2ze50r5zf6w69nf22rzphhlkzqzggvsclq47l"

[denoms]
deposit_token = "ibc/0E293A7622DC9A6439DB60E6D234B5AF446962E27CA3AB44D0590603DFF6968E"
ntrn = "untrn"
maxbtc = "factory/neutron1j4sl8nf7fkpsptqtcw6hmd6t27varth57gmjrrswfkr2t85sj8sqf6ncrh/maxbtc"
supervault_lp = "factory/neutron1048engrh7u0ssphgfd8lgs05pyq7e4n9uh6u8g24f4uu23ay4s6qc0cm9g/BTC-BTC"

[accounts]
gaia_ica = "neutron12luunfdhzwzeqfwl7ed5m7l6x28relaknnc95lqnkke99tg85ajqpm0h64"
ica_deposit = "neutron13f4knqzuzatfeppvjga9mu7z4c42x6s4g9aykx7klcytr3g3e7nsuxd5em"
supervault_deposit = "neutron1859v3rt4r4p7556uf2dcv2l28w332hdusy0wgmzj9awye8ekcdvq2wqvyd"
settlement = "neutron1mhlrj908cq40anrkn0ed9d9cthfwpxg5hq8e6hc3jeaszcwt4w4ssg87qd"

[libraries]
maxbtc_issuer = "neutron1g2gjezzrps0ka6l0jk85u43x8vz6s7sz6lsgefj274zn32ltx96q9eej45"
clearing_queue = "neutron1s9hqrqktfg55tqsqcravzpgxpfeuppur7tq0vhu7mz9lks5qzxpq6lepac"
ica_transfer_gaia = "neutron1sx4yvgm9q20j57mm8mx6p3s0326ywglrsq6fcwexes9a36kd8wasl4l4rq"
supervault_lper = "neutron1r4atda6u0swwk8uvjfe8ckmdq5s0lw3chh2rmz858f6umddt2qgsv0p8xs"

[coprocessor_app_ids]
clearing_queue = "66c611c39cad1747351bbb3d62922f537ff1defe58a67655b5213247cc84e061"
