[general]
grpc_url = "http://grpc-xyphion.neutron-1.neutron.org"
grpc_port = "80"
chain_id = "neutron-1"
owner = "neutron17w0xj03v3jj7tj8uz998ga6he93ytxggnrf8zr"      # Should be Neutron multisig
strategist = "neutron17w0xj03v3jj7tj8uz998ga6he93ytxggnrf8zr" # Should be strategist address

[program]
deposit_token_on_neutron_denom = "ibc/B559A80D62249C8AA07A380E2A2BEA6E5CA9A6F079C912C3A9E9B494105E4F81" # USDC on Neutron
mars_credit_manager = "neutron1qdzn3l4kn7gsjna2tfpg3g3mwd6kunx4p50lfya59k02846xas6qslgs3r"              # prod Mars Credit Manager address

[coprocessor_app]
clearing_queue_coprocessor_app_id = "a865408704b50176d07ec8d99da9f043368554581432ab58a17a4d76cfe755cf"
