[general]
grpc_url = "http://grpc-xyphion.neutron-1.neutron.org"
grpc_port = "80"
chain_id      = "neutron-1"
owner         = "neutron17w0xj03v3jj7tj8uz998ga6he93ytxggnrf8zr" # Should be Neutron multisig
strategist    = "neutron17w0xj03v3jj7tj8uz998ga6he93ytxggnrf8zr" # Should be strategist address

[program]
deposit_token_on_neutron_denom = "ibc/B559A80D62249C8AA07A380E2A2BEA6E5CA9A6F079C912C3A9E9B494105E4F81"                # USDC on Neutron
supervault                     = "neutron1z4qky902yes9zl5eruwgdd2pgtlyeglunc0escf0a7n2xeyw97gqcr7u5u"                  # TBD after supervaults are deployed
supervault_asset1              = "ibc/0E293A7622DC9A6439DB60E6D234B5AF446962E27CA3AB44D0590603DFF6968E"                # WBTC
supervault_asset2              = "ibc/B559A80D62249C8AA07A380E2A2BEA6E5CA9A6F079C912C3A9E9B494105E4F81"                # USDC
supervault_lp_denom            = "factory/neutron1z4qky902yes9zl5eruwgdd2pgtlyeglunc0escf0a7n2xeyw97gqcr7u5u/BTC-USDC"

[coprocessor_app]
clearing_queue_coprocessor_app_id = "576a76db5fc5b0816a5842f3509634eb924ad2095101b202b487a59c26f36a9e"
