grpc_url = "http://rpc.neutron.quokkastake.io"
grpc_port = "9090"
chain_id = "neutron-1"
mars_credit_manager = "neutron1qdzn3l4kn7gsjna2tfpg3g3mwd6kunx4p50lfya59k02846xas6qslgs3r"
authorizations = "neutron1tpz4kplk9djcfkad5xq4rle6q5awz7pclt57dwgv6y75sdlq082qp6ww2n"
processor = "neutron14f7papylk7n7rja3w0uurdmpfhe32p5yeqwfw3jhvgzyu39zwwuqs6hak0"

[denoms]
deposit_token = "ibc/B559A80D62249C8AA07A380E2A2BEA6E5CA9A6F079C912C3A9E9B494105E4F81"
ntrn = "untrn"

[accounts]
deposit = "neutron1k0kn6khfclj2klzpejtk847ejfhcajjsqtqcja3q5glue5g5x6ns5v6lqv"
settlement = "neutron17a4c2tukmd9ylnwu4lgl9jrku8w380xzgcr8ajxh5vcfl909m39slanq6l"

[libraries]
mars_lending = "neutron10zkunyhd52qsw2hwy9cfxy3pm52r25t0p9425d5k89gunz3dnmgsmeclgt"
clearing_queue = "neutron1qf8hjlh0zuhshnfx7jpjac3ershcqqjfmyjxzhtl3wwa445pzfjqzweajt"

[coprocessor_app_ids]
clearing_queue = "a354a79198fa96039a106c5cdae5c469e8371dd42b745e827fe063f66dd72fe5"
