grpc_url = "http://grpc-xyphion.neutron-1.neutron.org"
grpc_port = "80"
chain_id = "neutron-1"
mars_credit_manager = "neutron1et4xza4pge3asumk8yxdx6qm85k9eplk0kathtkheln6znxsqheqfytsza"
authorizations = "neutron1mrrucsjaq38wf7ph20ct0exp8gurlkegcslc7m23m6adxadmn20qxy5g9z"
processor = "neutron1vkr6qlmugwqft65rkqe8m57j6s8n2ncvsjjvmxk7fsejd6vnsgcshcgm7r"

[denoms]
deposit_token = "ibc/0E293A7622DC9A6439DB60E6D234B5AF446962E27CA3AB44D0590603DFF6968E"
ntrn = "untrn"

[accounts]
ica = "neutron1qg4p3lr5l490cn30d6l2ff3uhv46zpyeulqm7njmhh6glscqmpys38qhht"
deposit = "neutron1768e9hksl9tfy7u6na8r65ynrlxy68uhz3ft5cwa0y3uj40phewqaz4v9j"
settlement = "neutron1p0gqczatdh34zxpgf90k0rd2s8jc8me26w70f5zl4gqurup49dasp4vszs"

[libraries]
mars_lending = "neutron1w6pge7h2yk3gg2yatsxv9n6lzypnrxevzh6mjlu9axlxg89wv8nsrsd3he"
clearing_queue = "neutron1mvwcfrmwu8hah0hzdwhysvqs9853h769dy5sgpec9exc2clzjahsv7f48s"
ica_transfer = "neutron1v5t2px2gx8kjfmaqf602ply85jv3efu4duxa5kzcklnq2zwl68lsluylww"

[coprocessor_app_ids]
clearing_queue = "b4e94573c75689f5b5163c66bb1fcaaf6e681106a4caad8c70ab0e8ca4cf6cb3"
