[package]
name    = "packages"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy                               = { workspace = true }
serde                               = { workspace = true }
valence-clearing-queue-supervaults  = { workspace = true }
log                                 = { workspace = true }
